name: KojoGame
version: ${project.version}
main: kojogame.koutachan.KojoGame
commands:
  start:
    permission: kojogame.start
    permission-message: §cあなたにはこのコマンドを実行する権限がありません！
  setsponges:
    permission: kojogame.setsponges
    permission-message: §cあなたにはこのコマンドを実行する権限がありません！
  setspawn:
    permission: kojogame.setspawn
    permission-message: §cあなたにはこのコマンドを実行する権限がありません！
  gm:
    permission: kojogame.GM
    permission-message: §cあなたにはこのコマンドを実行する権限がありません！
  debug:
    permission: kojogame.debug
    permission-message: §cあなたにはこのコマンドを実行する権限がありません！